<?php
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Sc5010;
use Illuminate\Http\Request;

class SC5010Controller extends Controller
{
    public function index(Request $request)
    {
        $query = Sc5010::query();

        if ($request->has('fecha_desde')) {
            $query->where('c5_emissao', '>=', $request->fecha_desde);
        }
        if ($request->has('fecha_hasta')) {
            $query->where('c5_emissao', '<=', $request->fecha_hasta);
        }

        $limit = $request->input('limit', 10);
        $data  = $query->paginate($limit);

        return response()->json(['data' => $data->items(), 'total' => $data->total(), 'per_page' => $limit], 200);
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'c5_filial'    => 'required|string|max:9',
            'c5_num'       => 'required|string|max:9',
            'c5_tipo'      => 'required|string|max:9',
            'c5_cliente'   => 'required|string|max:9',
            'c5_lojacli'   => 'required|string|max:9',
            'c5_client'    => 'required|string|max:9',
            'c5_lojaent'   => 'required|string|max:9',
            'c5_xnomcli'   => 'required|string|max:90',
            'c5_transp'    => 'required|string|max:9',
            'c5_naturez'   => 'required|string|max:90',
            'c5_tipocli'   => 'required|string|max:9',
            'c5_condpag'   => 'required|string|max:9',
            'c5_xoccli'    => 'required|string|max:90',
            'c5_xnumori'   => 'required|string|max:9',
            'c5_tabela'    => 'required|string|max:9',
            'c5_vend1'     => 'required|string|max:9',
            'c5_comis1'    => 'numeric|min:0',
            'c5_vend2'     => 'required|string|max:9',
            'c5_comis2'    => 'numeric|min:0',
            'c5_vend3'     => 'required|string|max:9',
            'c5_comis3'    => 'numeric|min:0',
            'c5_vend4'     => 'required|string|max:9',
            'c5_comis4'    => 'numeric|min:0',
            'c5_vend5'     => 'required|string|max:9',
            'c5_comis5'    => 'numeric|min:0',
            'c5_desc1'     => 'numeric|min:0',
            'c5_desc2'     => 'numeric|min:0',
            'c5_desc3'     => 'numeric|min:0',
            'c5_desc4'     => 'numeric|min:0',
            'c5_banco'     => 'required|string|max:9',
            'c5_descfi'    => 'numeric|min:0',
            'c5_emissao'   => 'required|string|max:9',
            'c5_cotacao'   => 'required|string|max:9',
            'c5_parc1'     => 'numeric|min:0',
            'c5_data1'     => 'required|string|max:9',
            'c5_parc2'     => 'numeric|min:0',
            'c5_data2'     => 'required|string|max:9',
            'c5_parc3'     => 'numeric|min:0',
            'c5_data3'     => 'required|string|max:9',
            'c5_parc4'     => 'numeric|min:0',
            'c5_despesa'   => 'numeric|min:0',
            'c5_fretaut'   => 'numeric|min:0',
            'c5_reajust'   => 'required|string|max:9',
            'c5_moeda'     => 'numeric|min:0',
            'c5_data4'     => 'required|string|max:9',
            'c5_tpfrete'   => 'required|string|max:9',
            'c5_frete'     => 'numeric|min:0',
            'c5_seguro'    => 'numeric|min:0',
            'c5_pesol'     => 'numeric|min:0',
            'c5_pbruto'    => 'numeric|min:0',
            'c5_reimp'     => 'numeric|min:0',
            'c5_redesp'    => 'required|string|max:9',
            'c5_volume1'   => 'numeric|min:0',
            'c5_volume2'   => 'numeric|min:0',
            'c5_volume3'   => 'numeric|min:0',
            'c5_volume4'   => 'numeric|min:0',
            'c5_especi1'   => 'required|string|max:90',
            'c5_especi2'   => 'required|string|max:90',
            'c5_especi3'   => 'required|string|max:90',
            'c5_inciss'    => 'required|string|max:9',
            'c5_liberok'   => 'required|string|max:9',
            'c5_ok'        => 'required|string|max:9',
            'c5_nota'      => 'required|string|max:92',
            'c5_serie'     => 'required|string|max:9',
            'c5_especi4'   => 'required|string|max:90',
            'c5_os'        => 'required|string|max:9',
            'c5_acrsfin'   => 'numeric|min:0',
            'c5_mennota'   => 'required|string|max:90',
            'c5_menpad'    => 'required|string|max:9',
            'c5_kitrep'    => 'required|string|max:9',
            'c5_tipotit'   => 'required|string|max:9',
            'c5_tiplib'    => 'required|string|max:9',
            'c5_tiporem'   => 'required|string|max:9',
            'c5_txmoeda'   => 'numeric|min:0',
            'c5_numprof'   => 'required|string|max:92',
            'c5_descont'   => 'numeric|min:0',
            'c5_pedexp'    => 'required|string|max:90',
            'c5_tpcarga'   => 'required|string|max:9',
            'c5_docger'    => 'required|string|max:9',
            'c5_dtlanc'    => 'required|string|max:9',
            'c5_pdescab'   => 'numeric|min:0',
            'c5_blq'       => 'required|string|max:9',
            'c5_contra'    => 'required|string|max:90',
            'c5_vlr_frt'   => 'numeric|min:0',
            'c5_mdcontr'   => 'required|string|max:95',
            'c5_mdnumed'   => 'required|string|max:9',
            'c5_gerawms'   => 'required|string|max:9',
            'c5_mdplani'   => 'required|string|max:9',
            'c5_solfre'    => 'required|string|max:9',
            'c5_fecent'    => 'required|string|max:9',
            'c5_solopc'    => 'required|string|max:9',
            'c5_catpv'     => 'required|string|max:9',
            'c5_orcres'    => 'required|string|max:9',
            'c5_estpres'   => 'required|string|max:9',
            'c5_canje'     => 'required|string|max:9',
            'c5_sugent'    => 'required|string|max:9',
            'c5_provent'   => 'required|string|max:9',
            'c5_origem'    => 'required|string|max:95',
            'c5_nument'    => 'required|string|max:9',
            'c5_coded'     => 'required|string|max:95',
            'c5_numpr'     => 'required|string|max:95',
            'c5_veiculo'   => 'required|string|max:9',
            'c5_liqprod'   => 'required|string|max:9',
            'c5_codemb'    => 'required|string|max:9',
            'c5_remctr'    => 'required|string|max:95',
            'c5_remrev'    => 'required|string|max:9',
            'c5_idioma'    => 'required|string|max:9',
            'c5_incoter'   => 'required|string|max:95',
            'c5_ecsedex'   => 'required|string|max:93',
            'c5_ecvincu'   => 'required|string|max:9',
            'c5_dttxref'   => 'required|string|max:9',
            'c5_txref'     => 'numeric|min:0',
            'c5_permiss'   => 'required|string|max:96',
            'c5_paisent'   => 'required|string|max:9',
            'c5_tpvent'    => 'required|string|max:9',
            'c5_moedtit'   => 'numeric|min:0',
            'c5_pedecom'   => 'required|string|max:90',
            'c5_rastr'     => 'required|string|max:90',
            'c5_status'    => 'required|string|max:9',
            'c5_fechse'    => 'required|string|max:9',
            'c5_codsaf'    => 'required|string|max:95',
            'c5_trcnum'    => 'required|string|max:95',
            'c5_msblql'    => 'required|string|max:9',
            'c5_ecpresn'   => 'required|string|max:9',
            'c5_voltaps'   => 'required|string|max:9',
            'c5_fecdse'    => 'required|string|max:9',
            'c5_filgct'    => 'required|string|max:9',
            'c5_prepemb'   => 'required|string|max:9',
            'c5_sdoc'      => 'required|string|max:9',
            'c5_sdocsub'   => 'required|string|max:9',
            'd_e_l_e_t_'   => 'required|string|max:9',
            'r_e_c_d_e_l_' => 'required|integer',
            'c5_xobs'      => 'required|string|max:900',
            'c5_xexp'      => 'required|string|max:9',
            'c5_coment'    => 'required|string|max:954',
            'c5_numext'    => 'required|string|max:96',
        ]);

        $sc5010 = Sc5010::create($data);
        return response()->json($sc5010, 201);
    }

    public function show($id)
    {
        $sc5010 = Sc5010::with('items')->findOrFail($id);
        return response()->json($sc5010);
    }

    public function update(Request $request, $id)
    {
        $sc5010 = Sc5010::findOrFail($id);
        $data   = $request->validate([
            'c5_filial'    => 'string|max:9',
            'c5_num'       => 'string|max:9',
            'c5_tipo'      => 'string|max:9',
            'c5_cliente'   => 'string|max:9',
            'c5_lojacli'   => 'string|max:9',
            'c5_client'    => 'string|max:9',
            'c5_lojaent'   => 'string|max:9',
            'c5_xnomcli'   => 'string|max:90',
            'c5_transp'    => 'string|max:9',
            'c5_naturez'   => 'string|max:90',
            'c5_tipocli'   => 'string|max:9',
            'c5_condpag'   => 'string|max:9',
            'c5_xoccli'    => 'string|max:90',
            'c5_xnumori'   => 'string|max:9',
            'c5_tabela'    => 'string|max:9',
            'c5_vend1'     => 'string|max:9',
            'c5_comis1'    => 'numeric|min:0',
            'c5_vend2'     => 'string|max:9',
            'c5_comis2'    => 'numeric|min:0',
            'c5_vend3'     => 'string|max:9',
            'c5_comis3'    => 'numeric|min:0',
            'c5_vend4'     => 'string|max:9',
            'c5_comis4'    => 'numeric|min:0',
            'c5_vend5'     => 'string|max:9',
            'c5_comis5'    => 'numeric|min:0',
            'c5_desc1'     => 'numeric|min:0',
            'c5_desc2'     => 'numeric|min:0',
            'c5_desc3'     => 'numeric|min:0',
            'c5_desc4'     => 'numeric|min:0',
            'c5_banco'     => 'string|max:9',
            'c5_descfi'    => 'numeric|min:0',
            'c5_emissao'   => 'string|max:9',
            'c5_cotacao'   => 'string|max:9',
            'c5_parc1'     => 'numeric|min:0',
            'c5_data1'     => 'string|max:9',
            'c5_parc2'     => 'numeric|min:0',
            'c5_data2'     => 'string|max:9',
            'c5_parc3'     => 'numeric|min:0',
            'c5_data3'     => 'string|max:9',
            'c5_parc4'     => 'numeric|min:0',
            'c5_despesa'   => 'numeric|min:0',
            'c5_fretaut'   => 'numeric|min:0',
            'c5_reajust'   => 'string|max:9',
            'c5_moeda'     => 'numeric|min:0',
            'c5_data4'     => 'string|max:9',
            'c5_tpfrete'   => 'string|max:9',
            'c5_frete'     => 'numeric|min:0',
            'c5_seguro'    => 'numeric|min:0',
            'c5_pesol'     => 'numeric|min:0',
            'c5_pbruto'    => 'numeric|min:0',
            'c5_reimp'     => 'numeric|min:0',
            'c5_redesp'    => 'string|max:9',
            'c5_volume1'   => 'numeric|min:0',
            'c5_volume2'   => 'numeric|min:0',
            'c5_volume3'   => 'numeric|min:0',
            'c5_volume4'   => 'numeric|min:0',
            'c5_especi1'   => 'string|max:90',
            'c5_especi2'   => 'string|max:90',
            'c5_especi3'   => 'string|max:90',
            'c5_inciss'    => 'string|max:9',
            'c5_liberok'   => 'string|max:9',
            'c5_ok'        => 'string|max:9',
            'c5_nota'      => 'string|max:92',
            'c5_serie'     => 'string|max:9',
            'c5_especi4'   => 'string|max:90',
            'c5_os'        => 'string|max:9',
            'c5_acrsfin'   => 'numeric|min:0',
            'c5_mennota'   => 'string|max:90',
            'c5_menpad'    => 'string|max:9',
            'c5_kitrep'    => 'string|max:9',
            'c5_tipotit'   => 'string|max:9',
            'c5_tiplib'    => 'string|max:9',
            'c5_tiporem'   => 'string|max:9',
            'c5_txmoeda'   => 'numeric|min:0',
            'c5_numprof'   => 'string|max:92',
            'c5_descont'   => 'numeric|min:0',
            'c5_pedexp'    => 'string|max:90',
            'c5_tpcarga'   => 'string|max:9',
            'c5_docger'    => 'string|max:9',
            'c5_dtlanc'    => 'string|max:9',
            'c5_pdescab'   => 'numeric|min:0',
            'c5_blq'       => 'string|max:9',
            'c5_contra'    => 'string|max:90',
            'c5_vlr_frt'   => 'numeric|min:0',
            'c5_mdcontr'   => 'string|max:95',
            'c5_mdnumed'   => 'string|max:9',
            'c5_gerawms'   => 'string|max:9',
            'c5_mdplani'   => 'string|max:9',
            'c5_solfre'    => 'string|max:9',
            'c5_fecent'    => 'string|max:9',
            'c5_solopc'    => 'string|max:9',
            'c5_catpv'     => 'string|max:9',
            'c5_orcres'    => 'string|max:9',
            'c5_estpres'   => 'string|max:9',
            'c5_canje'     => 'string|max:9',
            'c5_sugent'    => 'string|max:9',
            'c5_provent'   => 'string|max:9',
            'c5_origem'    => 'string|max:95',
            'c5_nument'    => 'string|max:9',
            'c5_coded'     => 'string|max:95',
            'c5_numpr'     => 'string|max:95',
            'c5_veiculo'   => 'string|max:9',
            'c5_liqprod'   => 'string|max:9',
            'c5_codemb'    => 'string|max:9',
            'c5_remctr'    => 'string|max:95',
            'c5_remrev'    => 'string|max:9',
            'c5_idioma'    => 'string|max:9',
            'c5_incoter'   => 'string|max:95',
            'c5_ecsedex'   => 'string|max:93',
            'c5_ecvincu'   => 'string|max:9',
            'c5_dttxref'   => 'string|max:9',
            'c5_txref'     => 'numeric|min:0',
            'c5_permiss'   => 'string|max:96',
            'c5_paisent'   => 'string|max:9',
            'c5_tpvent'    => 'string|max:9',
            'c5_moedtit'   => 'numeric|min:0',
            'c5_pedecom'   => 'string|max:90',
            'c5_rastr'     => 'string|max:90',
            'c5_status'    => 'string|max:9',
            'c5_fechse'    => 'string|max:9',
            'c5_codsaf'    => 'string|max:95',
            'c5_trcnum'    => 'string|max:95',
            'c5_msblql'    => 'string|max:9',
            'c5_ecpresn'   => 'string|max:9',
            'c5_voltaps'   => 'string|max:9',
            'c5_fecdse'    => 'string|max:9',
            'c5_filgct'    => 'string|max:9',
            'c5_prepemb'   => 'string|max:9',
            'c5_sdoc'      => 'string|max:9',
            'c5_sdocsub'   => 'string|max:9',
            'd_e_l_e_t_'   => 'string|max:9',
            'r_e_c_d_e_l_' => 'integer',
            'c5_xobs'      => 'string|max:900',
            'c5_xexp'      => 'string|max:9',
            'c5_coment'    => 'string|max:954',
            'c5_numext'    => 'string|max:96',
        ]);

        $sc5010->update($data);
        return response()->json($sc5010);
    }

    public function destroy($id)
    {
        $sc5010 = Sc5010::findOrFail($id);
        $sc5010->update(['d_e_l_e_t_' => ' ']);
        return response()->json(null, 204);
    }
}
