<?php
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Sc6010;
use Illuminate\Http\Request;

class SC6010Controller extends Controller
{
    public function index(Request $request)
    {
        $query = Sc6010::query();

        // Filtrar por número de pedido si viene en el request
        if ($request->has('c6_num')) {
            $query->where('c6_num', $request->c6_num);
        }

        // Solo artículos no eliminados
        $query->where('r_e_c_d_e_l_', 0);

        // Retornamos los datos ordenados por item
        return response()->json([
            'data' => $query->orderBy('c6_item')->get(),
        ], 200);
    }
    public function store(Request $request)
    {
        $data = $request->validate([
            'c6_filial'    => 'required|string|max:9',
            'c6_item'      => 'required|string|max:9',
            'c6_produto'   => 'required|string|max:95',
            'c6_descri'    => 'required|string|max:95',
            'c6_um'        => 'required|string|max:9',
            'c6_qtdven'    => 'numeric|min:0',
            'c6_prcven'    => 'numeric|min:0',
            'c6_valor'     => 'numeric|min:0',
            'c6_qtdlib'    => 'numeric|min:0',
            'c6_segum'     => 'required|string|max:9',
            'c6_qtdlib2'   => 'numeric|min:0',
            'c6_tes'       => 'required|string|max:9',
            'c6_unsven'    => 'numeric|min:0',
            'c6_local'     => 'required|string|max:9',
            'c6_qtdent'    => 'numeric|min:0',
            'c6_qtdent2'   => 'numeric|min:0',
            'c6_cf'        => 'required|string|max:9',
            'c6_cli'       => 'required|string|max:9',
            'c6_descont'   => 'numeric|min:0',
            'c6_valdesc'   => 'numeric|min:0',
            'c6_la'        => 'required|string|max:9',
            'c6_entreg'    => 'required|string|max:9',
            'c6_loja'      => 'required|string|max:9',
            'c6_nota'      => 'required|string|max:92',
            'c6_datfat'    => 'required|string|max:9',
            'c6_serie'     => 'required|string|max:9',
            'c6_num'       => 'required|string|max:9|exists:sc5010,c5_num',
            'c6_comis1'    => 'numeric|min:0',
            'c6_comis2'    => 'numeric|min:0',
            'c6_comis3'    => 'numeric|min:0',
            'c6_comis4'    => 'numeric|min:0',
            'c6_comis5'    => 'numeric|min:0',
            'c6_pedcli'    => 'required|string|max:9',
            'c6_prunit'    => 'numeric|min:0',
            'c6_bloquei'   => 'required|string|max:9',
            'c6_reserva'   => 'required|string|max:9',
            'c6_op'        => 'required|string|max:9',
            'c6_ok'        => 'required|string|max:9',
            'c6_nfori'     => 'required|string|max:92',
            'c6_seriori'   => 'required|string|max:9',
            'c6_itemori'   => 'required|string|max:9',
            'c6_ipidev'    => 'numeric|min:0',
            'c6_identb6'   => 'required|string|max:9',
            'c6_blq'       => 'required|string|max:9',
            'c6_picmret'   => 'numeric|min:0',
            'c6_codiss'    => 'required|string|max:9',
            'c6_grade'     => 'required|string|max:9',
            'c6_itemgrd'   => 'required|string|max:9',
            'c6_lotectl'   => 'required|string|max:90',
            'c6_numlote'   => 'required|string|max:9',
            'c6_dtvalid'   => 'required|string|max:9',
            'c6_numorc'    => 'required|string|max:9',
            'c6_chassi'    => 'required|string|max:95',
            'c6_opc'       => 'required|string|max:90',
            'c6_localiz'   => 'required|string|max:95',
            'c6_numseri'   => 'required|string|max:90',
            'c6_numop'     => 'required|string|max:9',
            'c6_itemop'    => 'required|string|max:9',
            'c6_clasfis'   => 'required|string|max:9',
            'c6_qtdrese'   => 'numeric|min:0',
            'c6_contrat'   => 'required|string|max:9',
            'c6_numos'     => 'required|string|max:94',
            'c6_numosfa'   => 'required|string|max:94',
            'c6_codfab'    => 'required|string|max:9',
            'c6_lojafa'    => 'required|string|max:9',
            'c6_itemcon'   => 'required|string|max:9',
            'c6_tpop'      => 'required|string|max:9',
            'c6_revisao'   => 'required|string|max:9',
            'c6_geranf'    => 'required|string|max:9',
            'c6_locdest'   => 'required|string|max:9',
            'c6_servic'    => 'required|string|max:9',
            'c6_endpad'    => 'required|string|max:95',
            'c6_tpestr'    => 'required|string|max:9',
            'c6_contrt'    => 'required|string|max:95',
            'c6_tpcontr'   => 'required|string|max:9',
            'c6_itcontr'   => 'required|string|max:9',
            'c6_geroupv'   => 'required|string|max:9',
            'c6_projpms'   => 'required|string|max:90',
            'c6_edtpms'    => 'required|string|max:92',
            'c6_taskpms'   => 'required|string|max:92',
            'c6_trt'       => 'required|string|max:9',
            'c6_qtdemp'    => 'numeric|min:0',
            'c6_qtdemp2'   => 'numeric|min:0',
            'c6_projet'    => 'required|string|max:9',
            'c6_itproj'    => 'required|string|max:9',
            'c6_potenci'   => 'numeric|min:0',
            'c6_licita'    => 'required|string|max:9',
            'c6_regwms'    => 'required|string|max:9',
            'c6_mopc'      => 'nullable|binary',
            'c6_numcp'     => 'required|string|max:92',
            'c6_numsc'     => 'required|string|max:9',
            'c6_itemsc'    => 'required|string|max:9',
            'c6_sugentr'   => 'required|string|max:9',
            'c6_itemed'    => 'required|string|max:9',
            'c6_funrura'   => 'numeric|min:0',
            'c6_fetab'     => 'numeric|min:0',
            'c6_codrom'    => 'required|string|max:90',
            'c6_program'   => 'required|string|max:90',
            'c6_turno'     => 'required|string|max:9',
            'c6_pedcom'    => 'required|string|max:9',
            'c6_itpc'      => 'required|string|max:9',
            'c6_filped'    => 'required|string|max:9',
            'c6_codlan'    => 'required|string|max:9',
            'c6_gcplt'     => 'required|string|max:9',
            'c6_gcpit'     => 'required|string|max:9',
            'c6_categ'     => 'required|string|max:9',
            'c6_ctvar'     => 'required|string|max:90',
            'c6_solcom'    => 'required|string|max:9',
            'c6_vdmost'    => 'required|string|max:9',
            'c6_vdobs'     => 'nullable|binary',
            'c6_pvcomop'   => 'required|string|max:9',
            'c6_itemgar'   => 'required|string|max:9',
            'c6_orcgar'    => 'required|string|max:9',
            'c6_horent'    => 'required|string|max:9',
            'c6_almterc'   => 'required|string|max:9',
            'c6_itempc'    => 'required|string|max:9',
            'c6_numpcom'   => 'required|string|max:95',
            'c6_pene'      => 'required|string|max:9',
            'c6_ccusto'    => 'required|string|max:9',
            'c6_cc'        => 'required|string|max:9',
            'c6_pmsid'     => 'required|string|max:90',
            'c6_rateio'    => 'required|string|max:9',
            'c6_d1serie'   => 'required|string|max:9',
            'c6_sdoc'      => 'required|string|max:9',
            'c6_sdocded'   => 'required|string|max:9',
            'c6_sdocsd1'   => 'required|string|max:9',
            'c6_sdocori'   => 'required|string|max:9',
            'c6_cultra'    => 'required|string|max:90',
            'c6_codinf'    => 'required|string|max:9',
            'c6_codlpre'   => 'required|string|max:9',
            'c6_d1item'    => 'required|string|max:9',
            'c6_itlpre'    => 'required|string|max:9',
            'c6_d1doc'     => 'required|string|max:95',
            'c6_revprod'   => 'required|string|max:9',
            'c6_prodfin'   => 'required|string|max:95',
            'c6_pedvinc'   => 'required|string|max:9',
            'c6_tpprod'    => 'required|string|max:9',
            'c6_provent'   => 'required|string|max:9',
            'd_e_l_e_t_'   => 'required|string|max:9',
            'r_e_c_n_o_'   => 'required|integer',
            'r_e_c_d_e_l_' => 'required|integer',
            'c6_xconv'     => 'numeric|min:0',
            'c6_xcenvli'   => 'required|string|max:90',
            'c6_xcodcli'   => 'required|string|max:95',
            'c6_xoccli'    => 'required|string|max:90',
            'c6_oper'      => 'required|string|max:9',
        ]);

        $sc6010 = Sc6010::create($data);
        return response()->json($sc6010, 201);
    }

    public function show($id)
    {
        $sc6010 = Sc6010::with('order')->findOrFail($id);
        return response()->json($sc6010);
    }

    public function update(Request $request, $id)
    {
        $sc6010 = Sc6010::findOrFail($id);
        $data   = $request->validate([
            'c6_filial'    => 'string|max:9',
            'c6_item'      => 'string|max:9',
            'c6_produto'   => 'string|max:95',
            'c6_descri'    => 'string|max:95',
            'c6_um'        => 'string|max:9',
            'c6_qtdven'    => 'numeric|min:0',
            'c6_prcven'    => 'numeric|min:0',
            'c6_valor'     => 'numeric|min:0',
            'c6_qtdlib'    => 'numeric|min:0',
            'c6_segum'     => 'string|max:9',
            'c6_qtdlib2'   => 'numeric|min:0',
            'c6_tes'       => 'string|max:9',
            'c6_unsven'    => 'numeric|min:0',
            'c6_local'     => 'string|max:9',
            'c6_qtdent'    => 'numeric|min:0',
            'c6_qtdent2'   => 'numeric|min:0',
            'c6_cf'        => 'string|max:9',
            'c6_cli'       => 'string|max:9',
            'c6_descont'   => 'numeric|min:0',
            'c6_valdesc'   => 'numeric|min:0',
            'c6_la'        => 'string|max:9',
            'c6_entreg'    => 'string|max:9',
            'c6_loja'      => 'string|max:9',
            'c6_nota'      => 'string|max:92',
            'c6_datfat'    => 'string|max:9',
            'c6_serie'     => 'string|max:9',
            'c6_num'       => 'required|string|max:9|exists:sc5010,c5_num',
            'c6_comis1'    => 'numeric|min:0',
            'c6_comis2'    => 'numeric|min:0',
            'c6_comis3'    => 'numeric|min:0',
            'c6_comis4'    => 'numeric|min:0',
            'c6_comis5'    => 'numeric|min:0',
            'c6_pedcli'    => 'string|max:9',
            'c6_prunit'    => 'numeric|min:0',
            'c6_bloquei'   => 'string|max:9',
            'c6_reserva'   => 'string|max:9',
            'c6_op'        => 'string|max:9',
            'c6_ok'        => 'string|max:9',
            'c6_nfori'     => 'string|max:92',
            'c6_seriori'   => 'string|max:9',
            'c6_itemori'   => 'string|max:9',
            'c6_ipidev'    => 'numeric|min:0',
            'c6_identb6'   => 'string|max:9',
            'c6_blq'       => 'string|max:9',
            'c6_picmret'   => 'numeric|min:0',
            'c6_codiss'    => 'string|max:9',
            'c6_grade'     => 'string|max:9',
            'c6_itemgrd'   => 'string|max:9',
            'c6_lotectl'   => 'string|max:90',
            'c6_numlote'   => 'string|max:9',
            'c6_dtvalid'   => 'string|max:9',
            'c6_numorc'    => 'string|max:9',
            'c6_chassi'    => 'string|max:95',
            'c6_opc'       => 'string|max:90',
            'c6_localiz'   => 'string|max:95',
            'c6_numseri'   => 'string|max:90',
            'c6_numop'     => 'string|max:9',
            'c6_itemop'    => 'string|max:9',
            'c6_clasfis'   => 'string|max:9',
            'c6_qtdrese'   => 'numeric|min:0',
            'c6_contrat'   => 'string|max:9',
            'c6_numos'     => 'string|max:94',
            'c6_numosfa'   => 'string|max:94',
            'c6_codfab'    => 'string|max:9',
            'c6_lojafa'    => 'string|max:9',
            'c6_itemcon'   => 'string|max:9',
            'c6_tpop'      => 'string|max:9',
            'c6_revisao'   => 'string|max:9',
            'c6_geranf'    => 'string|max:9',
            'c6_locdest'   => 'string|max:9',
            'c6_servic'    => 'string|max:9',
            'c6_endpad'    => 'string|max:95',
            'c6_tpestr'    => 'string|max:9',
            'c6_contrt'    => 'string|max:95',
            'c6_tpcontr'   => 'string|max:9',
            'c6_itcontr'   => 'string|max:9',
            'c6_geroupv'   => 'string|max:9',
            'c6_projpms'   => 'string|max:90',
            'c6_edtpms'    => 'string|max:92',
            'c6_taskpms'   => 'string|max:92',
            'c6_trt'       => 'string|max:9',
            'c6_qtdemp'    => 'numeric|min:0',
            'c6_qtdemp2'   => 'numeric|min:0',
            'c6_projet'    => 'string|max:9',
            'c6_itproj'    => 'string|max:9',
            'c6_potenci'   => 'numeric|min:0',
            'c6_licita'    => 'string|max:9',
            'c6_regwms'    => 'string|max:9',
            'c6_mopc'      => 'nullable|binary',
            'c6_numcp'     => 'string|max:92',
            'c6_numsc'     => 'string|max:9',
            'c6_itemsc'    => 'string|max:9',
            'c6_sugentr'   => 'string|max:9',
            'c6_itemed'    => 'string|max:9',
            'c6_funrura'   => 'numeric|min:0',
            'c6_fetab'     => 'numeric|min:0',
            'c6_codrom'    => 'string|max:90',
            'c6_program'   => 'string|max:90',
            'c6_turno'     => 'string|max:9',
            'c6_pedcom'    => 'string|max:9',
            'c6_itpc'      => 'string|max:9',
            'c6_filped'    => 'string|max:9',
            'c6_codlan'    => 'string|max:9',
            'c6_gcplt'     => 'string|max:9',
            'c6_gcpit'     => 'string|max:9',
            'c6_categ'     => 'string|max:9',
            'c6_ctvar'     => 'string|max:90',
            'c6_solcom'    => 'string|max:9',
            'c6_vdmost'    => 'string|max:9',
            'c6_vdobs'     => 'nullable|binary',
            'c6_pvcomop'   => 'string|max:9',
            'c6_itemgar'   => 'string|max:9',
            'c6_orcgar'    => 'string|max:9',
            'c6_horent'    => 'string|max:9',
            'c6_almterc'   => 'string|max:9',
            'c6_itempc'    => 'string|max:9',
            'c6_numpcom'   => 'string|max:95',
            'c6_pene'      => 'string|max:9',
            'c6_ccusto'    => 'string|max:9',
            'c6_cc'        => 'string|max:9',
            'c6_pmsid'     => 'string|max:90',
            'c6_rateio'    => 'string|max:9',
            'c6_d1serie'   => 'string|max:9',
            'c6_sdoc'      => 'string|max:9',
            'c6_sdocded'   => 'string|max:9',
            'c6_sdocsd1'   => 'string|max:9',
            'c6_sdocori'   => 'string|max:9',
            'c6_cultra'    => 'string|max:90',
            'c6_codinf'    => 'string|max:9',
            'c6_codlpre'   => 'string|max:9',
            'c6_d1item'    => 'string|max:9',
            'c6_itlpre'    => 'string|max:9',
            'c6_d1doc'     => 'string|max:95',
            'c6_revprod'   => 'string|max:9',
            'c6_prodfin'   => 'string|max:95',
            'c6_pedvinc'   => 'string|max:9',
            'c6_tpprod'    => 'string|max:9',
            'c6_provent'   => 'string|max:9',
            'd_e_l_e_t_'   => 'string|max:9',
            'r_e_c_n_o_'   => 'integer',
            'r_e_c_d_e_l_' => 'integer',
            'c6_xconv'     => 'numeric|min:0',
            'c6_xcenvli'   => 'string|max:90',
            'c6_xcodcli'   => 'string|max:95',
            'c6_xoccli'    => 'string|max:90',
            'c6_oper'      => 'string|max:9',
        ]);

        $sc6010->update($data);
        return response()->json($sc6010);
    }

    public function destroy($id)
    {
        $sc6010 = Sc6010::findOrFail($id);
        $sc6010->update(['d_e_l_e_t_' => ' ']);
        return response()->json(null, 204);
    }
}
