<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Sc5010 extends Model
{
    protected $connection = 'ocr_capyc_vendedores';

    protected $table      = 'sc5010';
    protected $primaryKey = 'r_e_c_n_o_';
    public $incrementing  = false; // si r_e_c_n_o_ no es autoincremental
    protected $keyType    = 'int'; // o 'string' según corresponda
    public $timestamps    = false;

    protected $fillable = [
        'c5_filial',
        'c5_num',
        'c5_tipo',
        'c5_cliente',
        'c5_lojacli',
        'c5_client',
        'c5_lojaent',
        'c5_xnomcli',
        'c5_transp',
        'c5_naturez',
        'c5_tipocli',
        'c5_condpag',
        'c5_xoccli',
        'c5_xnumori',
        'c5_tabela',
        'c5_vend1',
        'c5_comis1',
        'c5_vend2',
        'c5_comis2',
        'c5_vend3',
        'c5_comis3',
        'c5_vend4',
        'c5_comis4',
        'c5_vend5',
        'c5_comis5',
        'c5_desc1',
        'c5_desc2',
        'c5_desc3',
        'c5_desc4',
        'c5_banco',
        'c5_descfi',
        'c5_emissao',
        'c5_cotacao',
        'c5_parc1',
        'c5_data1',
        'c5_parc2',
        'c5_data2',
        'c5_parc3',
        'c5_data3',
        'c5_parc4',
        'c5_despesa',
        'c5_fretaut',
        'c5_reajust',
        'c5_moeda',
        'c5_data4',
        'c5_tpfrete',
        'c5_frete',
        'c5_seguro',
        'c5_pesol',
        'c5_pbruto',
        'c5_reimp',
        'c5_redesp',
        'c5_volume1',
        'c5_volume2',
        'c5_volume3',
        'c5_volume4',
        'c5_especi1',
        'c5_especi2',
        'c5_especi3',
        'c5_inciss',
        'c5_liberok',
        'c5_ok',
        'c5_nota',
        'c5_serie',
        'c5_especi4',
        'c5_os',
        'c5_acrsfin',
        'c5_mennota',
        'c5_menpad',
        'c5_kitrep',
        'c5_tipotit',
        'c5_tiplib',
        'c5_tiporem',
        'c5_txmoeda',
        'c5_numprof',
        'c5_descont',
        'c5_pedexp',
        'c5_tpcarga',
        'c5_docger',
        'c5_dtlanc',
        'c5_pdescab',
        'c5_blq',
        'c5_contra',
        'c5_vlr_frt',
        'c5_mdcontr',
        'c5_mdnumed',
        'c5_gerawms',
        'c5_mdplani',
        'c5_solfre',
        'c5_fecent',
        'c5_solopc',
        'c5_catpv',
        'c5_orcres',
        'c5_estpres',
        'c5_canje',
        'c5_sugent',
        'c5_provent',
        'c5_origem',
        'c5_nument',
        'c5_coded',
        'c5_numpr',
        'c5_veiculo',
        'c5_liqprod',
        'c5_codemb',
        'c5_remctr',
        'c5_remrev',
        'c5_idioma',
        'c5_incoter',
        'c5_ecsedex',
        'c5_ecvincu',
        'c5_dttxref',
        'c5_txref',
        'c5_permiss',
        'c5_paisent',
        'c5_tpvent',
        'c5_moedtit',
        'c5_pedecom',
        'c5_rastr',
        'c5_status',
        'c5_fechse',
        'c5_codsaf',
        'c5_trcnum',
        'c5_msblql',
        'c5_ecpresn',
        'c5_voltaps',
        'c5_fecdse',
        'c5_filgct',
        'c5_prepemb',
        'c5_sdoc',
        'c5_sdocsub',
        'd_e_l_e_t_',
        'r_e_c_d_e_l_',
        'c5_xobs',
        'c5_xpdf', // 👈 NUEVO
        'c5_xexp',
        'c5_coment',
        'c5_numext',
        'estado_ocs',
    ];

    protected $casts = [
        'c5_comis1'  => 'double',
        'c5_comis2'  => 'double',
        'c5_comis3'  => 'double',
        'c5_comis4'  => 'double',
        'c5_comis5'  => 'double',
        'c5_desc1'   => 'double',
        'c5_desc2'   => 'double',
        'c5_desc3'   => 'double',
        'c5_desc4'   => 'double',
        'c5_descfi'  => 'double',
        'c5_parc1'   => 'double',
        'c5_parc2'   => 'double',
        'c5_parc3'   => 'double',
        'c5_parc4'   => 'double',
        'c5_despesa' => 'double',
        'c5_fretaut' => 'double',
        'c5_moeda'   => 'double',
        'c5_frete'   => 'double',
        'c5_seguro'  => 'double',
        'c5_pesol'   => 'double',
        'c5_pbruto'  => 'double',
        'c5_reimp'   => 'double',
        'c5_volume1' => 'double',
        'c5_volume2' => 'double',
        'c5_volume3' => 'double',
        'c5_volume4' => 'double',
        'c5_acrsfin' => 'double',
        'c5_txmoeda' => 'double',
        'c5_descont' => 'double',
        'c5_pdescab' => 'double',
        'c5_vlr_frt' => 'double',
        'c5_txref'   => 'double',
        'c5_moedtit' => 'double',
    ];
    public function items()
    {
        return $this->hasMany(Sc6010::class, 'c6_num', 'c5_num');
    }
}
