<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Sc6010 extends Model
{
    protected $table      = 'sc6010';
    protected $primaryKey = 'id';
    public $incrementing  = true;
    public $timestamps    = true;

    protected $fillable = [
        'c6_filial',
        'c6_item',
        'c6_produto',
        'c6_descri',
        'c6_um',
        'c6_qtdven',
        'c6_prcven',
        'c6_valor',
        'c6_qtdlib',
        'c6_segum',
        'c6_qtdlib2',
        'c6_tes',
        'c6_unsven',
        'c6_local',
        'c6_qtdent',
        'c6_qtdent2',
        'c6_cf',
        'c6_cli',
        'c6_descont',
        'c6_valdesc',
        'c6_la',
        'c6_entreg',
        'c6_loja',
        'c6_nota',
        'c6_datfat',
        'c6_serie',
        'c6_num',
        'c6_comis1',
        'c6_comis2',
        'c6_comis3',
        'c6_comis4',
        'c6_comis5',
        'c6_pedcli',
        'c6_prunit',
        'c6_bloquei',
        'c6_reserva',
        'c6_op',
        'c6_ok',
        'c6_nfori',
        'c6_seriori',
        'c6_itemori',
        'c6_ipidev',
        'c6_identb6',
        'c6_blq',
        'c6_picmret',
        'c6_codiss',
        'c6_grade',
        'c6_itemgrd',
        'c6_lotectl',
        'c6_numlote',
        'c6_dtvalid',
        'c6_numorc',
        'c6_chassi',
        'c6_opc',
        'c6_localiz',
        'c6_numseri',
        'c6_numop',
        'c6_itemop',
        'c6_clasfis',
        'c6_qtdrese',
        'c6_contrat',
        'c6_numos',
        'c6_numosfa',
        'c6_codfab',
        'c6_lojafa',
        'c6_itemcon',
        'c6_tpop',
        'c6_revisao',
        'c6_geranf',
        'c6_locdest',
        'c6_servic',
        'c6_endpad',
        'c6_tpestr',
        'c6_contrt',
        'c6_tpcontr',
        'c6_itcontr',
        'c6_geroupv',
        'c6_projpms',
        'c6_edtpms',
        'c6_taskpms',
        'c6_trt',
        'c6_qtdemp',
        'c6_qtdemp2',
        'c6_projet',
        'c6_itproj',
        'c6_potenci',
        'c6_licita',
        'c6_regwms',
        'c6_mopc',
        'c6_numcp',
        'c6_numsc',
        'c6_itemsc',
        'c6_sugentr',
        'c6_itemed',
        'c6_funrura',
        'c6_fetab',
        'c6_codrom',
        'c6_program',
        'c6_turno',
        'c6_pedcom',
        'c6_itpc',
        'c6_filped',
        'c6_codlan',
        'c6_gcplt',
        'c6_gcpit',
        'c6_categ',
        'c6_ctvar',
        'c6_solcom',
        'c6_vdmost',
        'c6_vdobs',
        'c6_pvcomop',
        'c6_itemgar',
        'c6_orcgar',
        'c6_horent',
        'c6_almterc',
        'c6_itempc',
        'c6_numpcom',
        'c6_pene',
        'c6_ccusto',
        'c6_cc',
        'c6_pmsid',
        'c6_rateio',
        'c6_d1serie',
        'c6_sdoc',
        'c6_sdocded',
        'c6_sdocsd1',
        'c6_sdocori',
        'c6_cultra',
        'c6_codinf',
        'c6_codlpre',
        'c6_d1item',
        'c6_itlpre',
        'c6_d1doc',
        'c6_revprod',
        'c6_prodfin',
        'c6_pedvinc',
        'c6_tpprod',
        'c6_provent',
        'd_e_l_e_t_',
        'r_e_c_n_o_',
        'r_e_c_d_e_l_',
        'c6_xconv',
        'c6_xcenvli',
        'c6_xcodcli',
        'c6_xoccli',
        'c6_oper',
    ];

    protected $casts = [
        'c6_qtdven'  => 'double',
        'c6_prcven'  => 'double',
        'c6_valor'   => 'double',
        'c6_qtdlib'  => 'double',
        'c6_qtdlib2' => 'double',
        'c6_unsven'  => 'double',
        'c6_qtdent'  => 'double',
        'c6_qtdent2' => 'double',
        'c6_descont' => 'double',
        'c6_valdesc' => 'double',
        'c6_comis1'  => 'double',
        'c6_comis2'  => 'double',
        'c6_comis3'  => 'double',
        'c6_comis4'  => 'double',
        'c6_comis5'  => 'double',
        'c6_prunit'  => 'double',
        'c6_ipidev'  => 'double',
        'c6_picmret' => 'double',
        'c6_qtdrese' => 'double',
        'c6_qtdemp'  => 'double',
        'c6_qtdemp2' => 'double',
        'c6_potenci' => 'double',
        'c6_funrura' => 'double',
        'c6_fetab'   => 'double',
        'c6_xconv'   => 'double',
    ];
    public function order()
    {
        return $this->belongsTo(Sc5010::class, 'c6_num', 'c5_num');
    }
}
